import type { CustomerListQuery, PaginatedResult } from '@oh/contracts';
export declare function useCustomers(query: Partial<CustomerListQuery>): import("@tanstack/react-query").UseQueryResult<NoInfer<PaginatedResult<{
    code: string;
    status: "ACTIVE" | "INACTIVE" | "BLOCKED";
    id: string;
    createdAt: string;
    email: string | null;
    name: string;
    company: string | null;
    phone: string | null;
    phoneAlt: string | null;
    address: string | null;
    city: string | null;
    taxNumber: string | null;
    notes: string | null;
    tags: string[];
    creditLimit: string;
    paymentTermDays: number;
    balance: string;
    accountState: "DEBIT" | "CREDIT" | "SETTLED";
    availableCredit: string;
    updatedAt: string;
    archivedAt: string | null;
}>>, Error>;
export declare function useCustomerStats(): import("@tanstack/react-query").UseQueryResult<NoInfer<{
    total: number;
    overCreditLimit: number;
    active: number;
    withDebt: number;
    totalDebt: string;
}>, Error>;
export declare function useCustomer(id: string | undefined): import("@tanstack/react-query").UseQueryResult<NoInfer<{
    code: string;
    status: "ACTIVE" | "INACTIVE" | "BLOCKED";
    id: string;
    createdAt: string;
    email: string | null;
    name: string;
    company: string | null;
    phone: string | null;
    phoneAlt: string | null;
    address: string | null;
    city: string | null;
    taxNumber: string | null;
    notes: string | null;
    tags: string[];
    creditLimit: string;
    paymentTermDays: number;
    balance: string;
    accountState: "DEBIT" | "CREDIT" | "SETTLED";
    availableCredit: string;
    updatedAt: string;
    archivedAt: string | null;
}>, Error>;
export declare function useCustomerSummary(id: string | undefined): import("@tanstack/react-query").UseQueryResult<NoInfer<{
    customer: {
        code: string;
        status: "ACTIVE" | "INACTIVE" | "BLOCKED";
        id: string;
        createdAt: string;
        email: string | null;
        name: string;
        company: string | null;
        phone: string | null;
        phoneAlt: string | null;
        address: string | null;
        city: string | null;
        taxNumber: string | null;
        notes: string | null;
        tags: string[];
        creditLimit: string;
        paymentTermDays: number;
        balance: string;
        accountState: "DEBIT" | "CREDIT" | "SETTLED";
        availableCredit: string;
        updatedAt: string;
        archivedAt: string | null;
    };
    totalOrders: number;
    totalOrdersAmount: string;
    totalPayments: number;
    totalPaymentsAmount: string;
    lastOrderAt: string | null;
    lastPaymentAt: string | null;
    overdueOrders: number;
    overdueAmount: string;
    avgPaymentDays: number | null;
    creditUsagePct: number | null;
    customerHealth: "EXCELLENT" | "GOOD" | "WARNING" | "AT_RISK";
}>, Error>;
export declare function useCreateCustomer(): import("@tanstack/react-query").UseMutationResult<{
    code: string;
    status: "ACTIVE" | "INACTIVE" | "BLOCKED";
    id: string;
    createdAt: string;
    email: string | null;
    name: string;
    company: string | null;
    phone: string | null;
    phoneAlt: string | null;
    address: string | null;
    city: string | null;
    taxNumber: string | null;
    notes: string | null;
    tags: string[];
    creditLimit: string;
    paymentTermDays: number;
    balance: string;
    accountState: "DEBIT" | "CREDIT" | "SETTLED";
    availableCredit: string;
    updatedAt: string;
    archivedAt: string | null;
}, Error, {
    status: "ACTIVE" | "INACTIVE" | "BLOCKED";
    name: string;
    tags: string[];
    creditLimit: string;
    paymentTermDays: number;
    openingBalance: string;
    email?: string | undefined;
    company?: string | undefined;
    phone?: string | undefined;
    phoneAlt?: string | undefined;
    address?: string | undefined;
    city?: string | undefined;
    taxNumber?: string | undefined;
    notes?: string | undefined;
}, unknown>;
export declare function useUpdateCustomer(id: string): import("@tanstack/react-query").UseMutationResult<{
    code: string;
    status: "ACTIVE" | "INACTIVE" | "BLOCKED";
    id: string;
    createdAt: string;
    email: string | null;
    name: string;
    company: string | null;
    phone: string | null;
    phoneAlt: string | null;
    address: string | null;
    city: string | null;
    taxNumber: string | null;
    notes: string | null;
    tags: string[];
    creditLimit: string;
    paymentTermDays: number;
    balance: string;
    accountState: "DEBIT" | "CREDIT" | "SETTLED";
    availableCredit: string;
    updatedAt: string;
    archivedAt: string | null;
}, Error, {
    status?: "ACTIVE" | "INACTIVE" | "BLOCKED" | undefined;
    email?: string | undefined;
    name?: string | undefined;
    company?: string | undefined;
    phone?: string | undefined;
    phoneAlt?: string | undefined;
    address?: string | undefined;
    city?: string | undefined;
    taxNumber?: string | undefined;
    notes?: string | undefined;
    tags?: string[] | undefined;
    creditLimit?: string | undefined;
    paymentTermDays?: number | undefined;
}, unknown>;
export declare function useArchiveCustomer(): import("@tanstack/react-query").UseMutationResult<void, Error, string, unknown>;
//# sourceMappingURL=api.d.ts.map