import type { CreateOrderRequest, OrderListQuery, PaginatedResult } from '@oh/contracts';
export declare function useOrders(query: Partial<OrderListQuery>): import("@tanstack/react-query").UseQueryResult<NoInfer<PaginatedResult<{
    number: string;
    id: string;
    notes: string | null;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    createdAt: string;
    total: string;
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    paidAmount: string;
    remainingAmount: string;
    isLocked: boolean;
    isOverdue: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
}>>, Error>;
export declare function useOrderStats(query: Partial<OrderListQuery>): import("@tanstack/react-query").UseQueryResult<NoInfer<{
    total: number;
    draft: number;
    quote: number;
    confirmed: number;
    partiallyPaid: number;
    paid: number;
    cancelled: number;
    totalAmount: string;
    outstandingAmount: string;
}>, Error>;
export declare function useOrder(id: string | undefined): import("@tanstack/react-query").UseQueryResult<NoInfer<{
    number: string;
    id: string;
    notes: string | null;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    createdAt: string;
    total: string;
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    paidAmount: string;
    remainingAmount: string;
    isLocked: boolean;
    isOverdue: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
    items: {
        id: string;
        name: string;
        sortOrder: number;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        sourceId: string | null;
        description: string | null;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        lineTotal: string;
    }[];
    allocations: {
        paymentId: string;
        paymentNumber: string;
        paidAt: string;
        method: string;
        amount: string;
    }[];
}>, Error>;
export declare function useCreateOrder(): import("@tanstack/react-query").UseMutationResult<{
    number: string;
    id: string;
    notes: string | null;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    createdAt: string;
    total: string;
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    paidAmount: string;
    remainingAmount: string;
    isLocked: boolean;
    isOverdue: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
    items: {
        id: string;
        name: string;
        sortOrder: number;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        sourceId: string | null;
        description: string | null;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        lineTotal: string;
    }[];
    allocations: {
        paymentId: string;
        paymentNumber: string;
        paidAt: string;
        method: string;
        amount: string;
    }[];
}, Error, {
    status: "DRAFT" | "QUOTE" | "CONFIRMED";
    customerId: string;
    discountAmount: string;
    items: {
        name: string;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        sourceId?: string | undefined;
        description?: string | undefined;
    }[];
    notes?: string | undefined;
    issuedAt?: string | undefined;
    dueAt?: string | undefined;
}, unknown>;
/** معاينة حساب الطلب — الخادم يحسب، الواجهة تعرض. */
export declare function usePreviewOrder(): import("@tanstack/react-query").UseMutationResult<{
    total: string;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    lineTotals: string[];
}, Error, {
    items: CreateOrderRequest["items"];
    discountAmount: string;
}, unknown>;
export declare function useConfirmOrder(id: string): import("@tanstack/react-query").UseMutationResult<{
    number: string;
    id: string;
    notes: string | null;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    createdAt: string;
    total: string;
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    paidAmount: string;
    remainingAmount: string;
    isLocked: boolean;
    isOverdue: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
    items: {
        id: string;
        name: string;
        sortOrder: number;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        sourceId: string | null;
        description: string | null;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        lineTotal: string;
    }[];
    allocations: {
        paymentId: string;
        paymentNumber: string;
        paidAt: string;
        method: string;
        amount: string;
    }[];
}, Error, {
    version: number;
    overrideCreditLimit: boolean;
    dueAt?: string | undefined;
    overrideReason?: string | undefined;
}, unknown>;
export declare function useCancelOrder(id: string): import("@tanstack/react-query").UseMutationResult<{
    number: string;
    id: string;
    notes: string | null;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    createdAt: string;
    total: string;
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    paidAmount: string;
    remainingAmount: string;
    isLocked: boolean;
    isOverdue: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
    items: {
        id: string;
        name: string;
        sortOrder: number;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        sourceId: string | null;
        description: string | null;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        lineTotal: string;
    }[];
    allocations: {
        paymentId: string;
        paymentNumber: string;
        paidAt: string;
        method: string;
        amount: string;
    }[];
}, Error, {
    version: number;
    reason: string;
}, unknown>;
//# sourceMappingURL=api.d.ts.map