import type { CreateOrderRequest, OrderListQuery, PaginatedResult } from '@oh/contracts';
export declare function useOrders(query: Partial<OrderListQuery>, enabled?: boolean): import("@tanstack/react-query").UseQueryResult<NoInfer<PaginatedResult<{
    number: string;
    id: string;
    createdAt: string;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    total: string;
    paidAmount: string;
    creditAppliedAmount: string;
    remainingAmount: string;
    notes: string | null;
    isLocked: boolean;
    isOverdue: boolean;
    isArchived: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
}>>, Error>;
export declare function useOrderStats(query: Partial<OrderListQuery>): import("@tanstack/react-query").UseQueryResult<NoInfer<{
    total: number;
    draft: number;
    quote: number;
    confirmed: number;
    partiallyPaid: number;
    paid: number;
    cancelled: number;
    totalAmount: string;
    outstandingAmount: string;
}>, Error>;
export declare function useOrder(id: string | undefined): import("@tanstack/react-query").UseQueryResult<NoInfer<{
    number: string;
    id: string;
    createdAt: string;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    total: string;
    paidAmount: string;
    creditAppliedAmount: string;
    remainingAmount: string;
    notes: string | null;
    isLocked: boolean;
    isOverdue: boolean;
    isArchived: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
    items: {
        id: string;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        sourceId: string | null;
        name: string;
        description: string | null;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        lineTotal: string;
        sortOrder: number;
    }[];
    allocations: {
        paymentId: string;
        paymentNumber: string;
        paidAt: string;
        method: string;
        amount: string;
    }[];
}>, Error>;
export declare function useCreateOrder(): import("@tanstack/react-query").UseMutationResult<{
    number: string;
    id: string;
    createdAt: string;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    total: string;
    paidAmount: string;
    creditAppliedAmount: string;
    remainingAmount: string;
    notes: string | null;
    isLocked: boolean;
    isOverdue: boolean;
    isArchived: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
    items: {
        id: string;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        sourceId: string | null;
        name: string;
        description: string | null;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        lineTotal: string;
        sortOrder: number;
    }[];
    allocations: {
        paymentId: string;
        paymentNumber: string;
        paidAt: string;
        method: string;
        amount: string;
    }[];
}, Error, {
    status: "DRAFT" | "QUOTE" | "CONFIRMED";
    customerId: string;
    discountAmount: string;
    items: {
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        name: string;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        sourceId?: string | undefined;
        description?: string | undefined;
    }[];
    issuedAt?: string | undefined;
    dueAt?: string | undefined;
    notes?: string | undefined;
}, unknown>;
export declare function useUpdateOrder(id: string): import("@tanstack/react-query").UseMutationResult<{
    number: string;
    id: string;
    createdAt: string;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    total: string;
    paidAmount: string;
    creditAppliedAmount: string;
    remainingAmount: string;
    notes: string | null;
    isLocked: boolean;
    isOverdue: boolean;
    isArchived: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
    items: {
        id: string;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        sourceId: string | null;
        name: string;
        description: string | null;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        lineTotal: string;
        sortOrder: number;
    }[];
    allocations: {
        paymentId: string;
        paymentNumber: string;
        paidAt: string;
        method: string;
        amount: string;
    }[];
}, Error, {
    version: number;
    customerId?: string | undefined;
    issuedAt?: string | undefined;
    dueAt?: string | undefined;
    discountAmount?: string | undefined;
    notes?: string | undefined;
    items?: {
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        name: string;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        sourceId?: string | undefined;
        description?: string | undefined;
    }[] | undefined;
}, unknown>;
/** معاينة حساب الطلب — الخادم يحسب، الواجهة تعرض. */
export declare function usePreviewOrder(): import("@tanstack/react-query").UseMutationResult<{
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    total: string;
    lineTotals: string[];
}, Error, {
    items: CreateOrderRequest["items"];
    discountAmount: string;
}, unknown>;
export declare function useConfirmOrder(id: string): import("@tanstack/react-query").UseMutationResult<{
    number: string;
    id: string;
    createdAt: string;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    total: string;
    paidAmount: string;
    creditAppliedAmount: string;
    remainingAmount: string;
    notes: string | null;
    isLocked: boolean;
    isOverdue: boolean;
    isArchived: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
    items: {
        id: string;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        sourceId: string | null;
        name: string;
        description: string | null;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        lineTotal: string;
        sortOrder: number;
    }[];
    allocations: {
        paymentId: string;
        paymentNumber: string;
        paidAt: string;
        method: string;
        amount: string;
    }[];
}, Error, {
    version: number;
    overrideCreditLimit: boolean;
    dueAt?: string | undefined;
    overrideReason?: string | undefined;
}, unknown>;
export declare function useCancelOrder(id: string): import("@tanstack/react-query").UseMutationResult<{
    number: string;
    id: string;
    createdAt: string;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    total: string;
    paidAmount: string;
    creditAppliedAmount: string;
    remainingAmount: string;
    notes: string | null;
    isLocked: boolean;
    isOverdue: boolean;
    isArchived: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
    items: {
        id: string;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        sourceId: string | null;
        name: string;
        description: string | null;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        lineTotal: string;
        sortOrder: number;
    }[];
    allocations: {
        paymentId: string;
        paymentNumber: string;
        paidAt: string;
        method: string;
        amount: string;
    }[];
}, Error, {
    version: number;
    reason: string;
}, unknown>;
export declare function useDuplicateOrder(): import("@tanstack/react-query").UseMutationResult<{
    number: string;
    id: string;
    createdAt: string;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    total: string;
    paidAmount: string;
    creditAppliedAmount: string;
    remainingAmount: string;
    notes: string | null;
    isLocked: boolean;
    isOverdue: boolean;
    isArchived: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
    items: {
        id: string;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        sourceId: string | null;
        name: string;
        description: string | null;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        lineTotal: string;
        sortOrder: number;
    }[];
    allocations: {
        paymentId: string;
        paymentNumber: string;
        paidAt: string;
        method: string;
        amount: string;
    }[];
}, Error, string, unknown>;
export declare function useDeleteOrder(): import("@tanstack/react-query").UseMutationResult<void, Error, {
    id: string;
    version: number;
}, unknown>;
export declare function useArchiveOrder(): import("@tanstack/react-query").UseMutationResult<{
    number: string;
    id: string;
    createdAt: string;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    total: string;
    paidAmount: string;
    creditAppliedAmount: string;
    remainingAmount: string;
    notes: string | null;
    isLocked: boolean;
    isOverdue: boolean;
    isArchived: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
    items: {
        id: string;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        sourceId: string | null;
        name: string;
        description: string | null;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        lineTotal: string;
        sortOrder: number;
    }[];
    allocations: {
        paymentId: string;
        paymentNumber: string;
        paidAt: string;
        method: string;
        amount: string;
    }[];
}, Error, {
    id: string;
    version: number;
    archived: boolean;
}, unknown>;
export declare function useRevertToDraft(): import("@tanstack/react-query").UseMutationResult<{
    number: string;
    id: string;
    createdAt: string;
    status: "DRAFT" | "QUOTE" | "CONFIRMED" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
    customerId: string;
    customerName: string;
    customerCode: string;
    issuedAt: string;
    dueAt: string | null;
    subtotal: string;
    discountAmount: string;
    taxAmount: string;
    total: string;
    paidAmount: string;
    creditAppliedAmount: string;
    remainingAmount: string;
    notes: string | null;
    isLocked: boolean;
    isOverdue: boolean;
    isArchived: boolean;
    itemCount: number;
    version: number;
    confirmedAt: string | null;
    cancelledAt: string | null;
    cancelReason: string | null;
    items: {
        id: string;
        sourceType: "MANUAL" | "PRODUCT" | "SERVICE";
        sourceId: string | null;
        name: string;
        description: string | null;
        quantity: string;
        unitPrice: string;
        discount: string;
        taxRate: string;
        lineTotal: string;
        sortOrder: number;
    }[];
    allocations: {
        paymentId: string;
        paymentNumber: string;
        paidAt: string;
        method: string;
        amount: string;
    }[];
}, Error, {
    id: string;
    version: number;
}, unknown>;
//# sourceMappingURL=api.d.ts.map